; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for CoinHeist:

; to see the correct usage look at the file, "musicMacro.s"

.export _music_data_coinheist:=music_data_coinheist

music_data_coinheist:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Song 2
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_coinheist
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env4,@env0 ; 00 : Lead
	.word @env5,@env2,@env3,@env0 ; 01 : Drums

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$08
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00
@env4:
	.byte $c2,$7f,$00,$00
@env5:
	.byte $00,$ce,$ca,$c5,$c0,$00,$04

@samples:

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $24, $8b, $24, $8b, $29, $97, $24, $97, $00, $97, $24, $89, $24, $8b, $29, $97, $24, $97, $00, $97, $26, $99, $28, $97
	.byte $24, $97, $00, $97, $26, $97, $28, $97, $26, $89, $28, $8b, $26, $8b, $28, $89, $48, $24, $8b, $24, $8b, $29, $97, $24
	.byte $97, $00, $97, $24, $97, $2b, $97, $26, $97, $00, $97, $26, $99, $28, $97, $24, $97, $00, $97, $26, $89, $28, $8b, $26
	.byte $8b, $28, $89, $26, $89, $28, $8b, $26, $8b, $28, $89, $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $52
	.word @song0ref6
	.byte $48
	.byte $41, $42
	.word @song0ref6
	.byte $24, $89, $26, $8b, $24, $8b, $26, $89, $24, $89, $21, $8b, $1f, $8b, $1a, $89, $48, $18, $e7, $00, $ff, $cf, $23, $89
	.byte $23, $8b, $24, $8b, $24, $89, $26, $89, $26, $8b, $28, $8b, $28, $89, $48, $00, $ff, $ff, $ff, $a1, $48, $ff, $ff, $ff
	.byte $a3, $48, $ff, $ff, $ff, $a3, $48, $ff, $ff, $ff, $a3, $48, $ff, $ff, $ff, $a3, $48, $ff, $ff, $ff, $a3, $48, $ff, $ff
	.byte $ff, $a3, $42
	.word @song0ch0loop
@song0ch4:
@song0ch2:
@song0ch1:
@song0ch1loop:
@song0ref181:
	.byte $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3, $ff, $ff, $ff, $a3
	.byte $41, $14
	.word @song0ref181
	.byte $41, $14
	.word @song0ref181
	.byte $ff, $ff, $ff, $a3, $42
	.word @song0ch1loop
@song0ch3:
@song0ch3loop:
	.byte $00, $99, $82
@song0ref218:
	.byte $32, $97, $00, $97, $32, $97, $00, $97, $32, $97, $00, $97, $32, $97, $00, $99, $32, $97, $00, $97, $32, $97, $00, $97
	.byte $32, $97, $00, $97, $32, $97, $00, $99
	.byte $41, $20
	.word @song0ref218
	.byte $41, $20
	.word @song0ref218
	.byte $41, $20
	.word @song0ref218
	.byte $41, $20
	.word @song0ref218
	.byte $41, $20
	.word @song0ref218
	.byte $41, $20
	.word @song0ref218
	.byte $41, $1c
	.word @song0ref218
	.byte $26, $97, $26, $8b, $00, $ff, $ff, $c5, $32, $97, $00, $97, $32, $97, $00, $ff, $ff, $ff, $a1
	.byte $41, $14
	.word @song0ref181
	.byte $ff, $ff, $ff, $a3, $42
	.word @song0ch3loop
